import { Router } from "express";
import * as controller from "../controllers/subscriptionController.js";
import { authenticate } from "../middleware/auth.middleware.js";
import { requireAdmin, requireUser } from "../middleware/rbac.middleware.js";
export const subscriptionRoutes=Router();
subscriptionRoutes.use(authenticate,requireUser);
subscriptionRoutes.get("/me",controller.mine);
subscriptionRoutes.post("/checkout",controller.checkout);
subscriptionRoutes.get("/payment-history",controller.history);
subscriptionRoutes.get("/payments/:orderId",controller.paymentStatus);
export const paymentRoutes=Router(); paymentRoutes.post("/midtrans/webhook",controller.webhook);
export const subscriptionAdminRoutes=Router(); subscriptionAdminRoutes.use(authenticate,requireAdmin);subscriptionAdminRoutes.get("/subscriptions",controller.adminSubscriptions);subscriptionAdminRoutes.get("/payments",controller.adminPayments);
